theme = "catppuccin_macchiato"

[editor]
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"

